### ISSUE TITLE
Remove "VOLUME /etc/grid-security" from Dockerfile

### ISSUE THREAD

**Issue by vbrik** [rucio/containers#11]
Would it be possible to remove the line `VOLUME /etc/grid-security` from Rucio Dockerfiles?

At IceCube we are running Rucio in a kubernetes cluster using modified containers from https://hub.docker.com/u/rucio. I'd like to use something like `FROM rucio/rucio-server` in my Dockerfiles but because of the line `VOLUME /etc/grid-security` the files I drop in /etc/grid-security when I build my container are not present when the container is deployed to kubernetes.

Making /etc/grid-security a volumeMount in kubernetes pods is not an attractive solution since we run several test instances of Rucio and using persistent storage for it would require some form of manual setup or clean-up. Populating /etc/grid-security when container is started also has obvious disadvantages. It would be much more convenient if our Rucio containers were as self-contained as possible.

**Comment by ericvaandering** [comment]
@tbeerman I've got the same issue and can issue a pull request.

With this line here, another container built off of this one can't have files there. If it's needed, I'd suggest splitting this container into two. 

I'll make a PR as I clean stuff up for the auth server in k8s.

**Comment by ericvaandering** [comment]
Fixed by #12
