### ISSUE TITLE
All daemons crashing with 1.23.11.post4

### ISSUE THREAD

**Issue by ericvaandering** [rucio/containers#114]
`/start-daemon.sh: Permission denied`

which makes me think the  1.23.11.post4 build picked up the python3-only change which went into containers.

**Comment by ericvaandering** [comment]
Nope, just a missed execution bit

**Comment by tbeerman** [comment]
With all the moving around and deleting of files in the new LTS release branches I accidentally deleted `start-daemon.sh` for py2 in 1.23. I added it again manually yesterday but forgot to set the right permissions. Thanks for your fix. I'll rebuild the py2 containers for 1.23.11.post4 locally and push them to docker hub.
