### ISSUE TITLE
Recent apache RPM breaks SSL auth server

### ISSUE THREAD

**Issue by ericvaandering** [rucio/containers#13]
In case anyone else has this too, it seems recent RPMs add a /etc/httpd/conf.d/ssl.conf file by default which also listens on port 443 such that the auth server cannot. 

I just add 
RUN rm /etc/httpd/conf.d/ssl.conf
to my docker file which then allows the auth server to work. If this is a more general issue, we should probably move it to the Rucio-server/Dockerfile here

**Comment by mlassnig** [comment]
Is there a chance that the modules on the docker will ever be updated? In our production nodes, we create 0-sized files, as these won't be touched by an RPM upgrade. Otherwise these files will always be recreated.

**Comment by ericvaandering** [comment]
I don’t follow you here. The newest httpd rpm is adding a file which didn’t exist before which is messing up the Auth server.

Sent from a mobile device. Please excuse my brevity or transcription errors.

On May 3, 2019, at 11:08, Mario Lassnig <notifications@github.com<mailto:notifications@github.com>> wrote:


Is there a chance that the modules on the docker will ever be updated? In our production nodes, we create 0-sized files, as these won't be touched by an RPM upgrade. Otherwise these files will always be recreated.

**Comment by ericvaandering** [comment]
And this went away with the 1.19.7.post1 container....
