### ISSUE TITLE
Rucio client for ARM (M1) processors?

### ISSUE THREAD

**Issue by tamasgal** [rucio/containers#143]
With reference to https://github.com/ESCAPE-WP2/Rucio-Client-Containers/issues/34 it seems that the main problem is that there is no `aarch64` version of the Docker image. This causes problems with at least the `libgfal_plugin_gridftp.so` library which is required to upload files, therefore, this functionality is not working when using e.g. a Mac(Book) with an M1 chip, which are getting more and more popular.

Is this a known issue? Are there any plans to offer cross-compiled arm64 images?

**Comment by mlassnig** [comment]
Hi, not much we can do here. I've created a ticket in the GFAL issue tracker: https://its.cern.ch/jira/browse/DMC-1255

**Comment by mlassnig** [comment]
Hi @tamasgal, as mentioned on the DMC Jira, it seems that Fedora builds EPEL for ARM by default, so the GFAL packages should be in there already.

**Comment by tamasgal** [comment]
OK thanks, this means that we need to rebuild the Rucio container in our ESCAPE repository.
