### ISSUE TITLE
Add support for Belle II specific tests

### ISSUE THREAD

**Issue by cserf** [rucio/containers#160]
In order to write Belle II specific tests, a new image including `rucio.cfg` with Belle II parameters is needed as well as a specific `rse_repository.json` that contains RSEs matching the RSE pattern (no underscore)

**Comment by bari12** [comment]
I am not entirely sure if we need separate images. Perhaps this can be handled via configuration of a new VO-testsuite (policies, etc.)?

**Comment by bari12** [comment]
Is this still needed with the Belle 2 VO tests working?

**Comment by bari12** [comment]
Ping @cserf
