### ISSUE TITLE
rucio client container reports: register-python-argcomplete: command not found

### ISSUE THREAD

**Issue by ygrange** [rucio/containers#169]
Heya,

I'm using the ESCAPE-derived Rucio client container (https://github.com/ESCAPE-WP2/Rucio-Client-Containers). When I start the container (either Singularity or docker) I get the following two errors:

```bash: register-python-argcomplete: command not found
bash: register-python-argcomplete: command not found
```
This seems to come from here:
https://github.com/rucio/containers/blob/master/clients/Dockerfile#L39
https://github.com/rucio/containers/blob/master/clients/init_rucio.sh#L14

I can make the error go away by installing the  python-argcomplete package, but that looks like a python2 package and I don;t really know whether it actualy fixes the functionality (because to be fair I don't really know how to test). I read on 'the Internet' that there is also a  python3-argcomplete package, but I couldn't find it in the yum repo.

So I decided not to just blindly do a pull request but open an issue so that someone who knows this much better than me could weigh in / investigate.

**Comment by bari12** [comment]
This is a consequence of removing `argcomplete` as a mandatory requirement in the rucio-clients package and moving it to optional.

Solution is to change https://github.com/rucio/containers/blob/master/clients/Dockerfile#L22
to
```
python3.6 -m pip install --no-cache-dir --pre rucio-clients[argcomplete]==$TAG && \
```
