### ISSUE TITLE
Disable Insecure TLS

### ISSUE THREAD

**Issue by bjwhite-fnal** [rucio/containers#175]
In order to allow the default Apache configuration for the server to be used at Fermilab in accordance with our security policies, I propose that TLS1.0/1.1 be disabled in the default configuration, with an option added to enable support for them if needed.

**Comment by bari12** [comment]
This seems reasonable. @bjwhite-fnal can you submit a PR for it?

**Comment by bjwhite-fnal** [comment]
Yes absolutely when I have a chance. I already have a solution which works for my needs.
