### ISSUE TITLE
Add WebUI 2.0 Dockerfile

### ISSUE THREAD

**Issue by maany** [rucio/containers#186]
Add support for https://github.com/rucio/webui

**Comment by sayang14** [comment]
Hi @maany , can I solve this issue as a part of this year's hacktoberfest? it will be grateful if you can help a little bit on how to proceed? thanks!

**Comment by maany** [comment]
Hi @sayang14, this has already been done: https://github.com/rucio/containers/pull/206. I should have closed it but thanks for trying to pick this one up.

**Comment by sayang14** [comment]
Is it possible for me to solve any issue in this repository as a part of this year's hacktoberfest ?
