### ISSUE TITLE
handle versioning for all containers

### ISSUE THREAD

**Issue by gabrielefronze** [rucio/containers#187]
Hello,

The `rucio-fs` container is based on the `rucio-clients` one, with the addition of the fuse-posix module.

Possibly, the release version of the `rucio-clients` and that of the fuse-posix module are unaligned and, at the same time, a new release of the fuse-posix module might occur asynchronously wrt the release path of the rucio clients.

This issue is aimed at evaluating the possibility to use a double tagging schema for the `rucio-fs` container, in order to be able to express both the underlying `rucio-clients` version as well as the fuse posix module version.

This should require a minor update of the repo and would allow to trigger a rebuild of the `rucio-fs` container in case of fixes unrelated to the current rucio clients version.

**Comment by rcarpa** [comment]
This must be done for all containers which are not currently versioned
