### ISSUE TITLE
Update fts docker container with token enabled release

### ISSUE THREAD

**Issue by bari12** [rucio/containers#266]
Please update the fts container so we can run integration tests with tokens.

From Steve:
> The RPM names and versions are as follows:
> 
> [c7] ~ > ssh root@fts-pilot-001.cern.ch 'rpm -qa | grep fts- | sort'
> fts-infosys-3.14.0-r2311081214git2ae3831.el7.cern.x86_64
> fts-libs-3.14.0-r2311081214git2ae3831.el7.cern.x86_64
> fts-monitoring-3.12.2-1.el7.cern.noarch
> fts-monitoring-selinux-3.12.2-1.el7.cern.noarch
> fts-msg-3.14.0-r2311081214git2ae3831.el7.cern.x86_64
> fts-mysql-3.14.0-r2311081214git2ae3831.el7.cern.x86_64
> fts-rest-client-3.12.4-1.el7.cern.noarch
> fts-rest-server-3.12.4-r2311091848gitfcc05d2.el7.cern.noarch
> fts-rest-server-selinux-3.12.4-r2311091848gitfcc05d2.el7.cern.noarch
> fts-server-3.14.0-r2311081214git2ae3831.el7.cern.x86_64
> fts-server-selinux-3.14.0-r2311081214git2ae3831.el7.cern.x86_64
> [c7] ~ >
> 
> Please note that the required GFAL2 version is 2.22.0-1
> 
> [c7] ~ > ssh root@fts-pilot-001.cern.ch 'rpm -qa | grep gfal2- | sort'
> gfal2-2.22.0-1.el7.cern.x86_64
> gfal2-plugin-dcap-2.22.0-1.el7.cern.x86_64
> gfal2-plugin-file-2.22.0-1.el7.cern.x86_64
> gfal2-plugin-gridftp-2.22.0-1.el7.cern.x86_64
> gfal2-plugin-http-2.22.0-1.el7.cern.x86_64
> gfal2-plugin-lfc-2.22.0-1.el7.cern.x86_64
> gfal2-plugin-mock-2.22.0-1.el7.cern.x86_64
> gfal2-plugin-rfio-2.22.0-1.el7.cern.x86_64
> gfal2-plugin-srm-2.22.0-1.el7.cern.x86_64
> gfal2-plugin-xrootd-2.22.0-1.el7.cern.x86_64
> python3-gfal2-1.12.0-1.el7.cern.x86_64
> [c7] ~ >
> 
> The FTS RPMs are located in the following YUM repository:
> 
>     https://fts-repo.web.cern.ch/fts-repo/testing/FTS-1925_token_project/el7/x86_64/
> 
> 
> The database schema creation file is located here:
> 
>     https://gitlab.cern.ch/fts/fts3/-/blob/FTS-1925_token_project/src/db/schema/mysql/fts-schema-9.0.0.sql?ref_type=heads

**Comment by rcarpa** [comment]
@mpatrascoiu, I'm re-iterating my argument that having FTS containers officially maintained by the FTS team would be very helpful.
