### ISSUE TITLE
client container configuration broken by a recent release

### ISSUE THREAD

**Issue by rcarpa** [rucio/containers#267]
We recently shifted to using the new merge rucio cfg script in the clients container: 
https://github.com/rucio/containers/commit/da1e4e4b64116259ed3c826014b00b41c159c988

However, for a reason which is beyond my capacity of understanding, the clients container was configured with different ENV variables than the others one. Other containers used the convention `RUCIO_CFG_Something_SomethingElse` to put the values in rucio.cfg. For example: `RUCIO_CFG_CLIENT_ACCOUNT` to populate 
```
[client]
account=
```

While the client container re-used a different list of variables, skipping the _CLIENT part:

https://github.com/rucio/containers/tree/32.0.0/clients#rucio_cfg-configuration-parameters

As a result, the recent change to homogenize the client container to others have broken it: 
https://github.com/rucio/containers/commit/da1e4e4b64116259ed3c826014b00b41c159c988
https://github.com/rucio/containers/commit/bf4aa98a83c86d20256c416ff1b1c35190c0d354

**Comment by rcarpa** [comment]
I propose to just update the documentation with the new variable names. The breaking change being already online for many months, I don't think it's justified to implement a workaround. At least, it will get rid of this old inconsistency.

**Comment by maxnoe** [comment]
The README on dockerhub lists the old values, which is misleading...

https://hub.docker.com/r/rucio/rucio-clients/tags

I think this is because you released updated versions of older releases (24 days ago) but the "latest" tag is one month old and it seems dockerhub is using the last push for the readme.

Could you update this so the README on dockerhub shows the correct usage?

**Comment by rcarpa** [comment]
Should be OK now. It was pushed automatically by the last rucio release.

**Comment by maxnoe** [comment]
@rcarpa I still see the old variables here:

https://hub.docker.com/r/rucio/rucio-clients

under "getting started"

**Comment by maxnoe** [comment]
Maybe you need to manually update the readme?

**Comment by rcarpa** [comment]
Seems like the README doesn't sync automatically :thinking: updated them manually. Thanks for reporting
