### ISSUE TITLE
fts images use centos 7 as base

### ISSUE THREAD

**Issue by maxnoe** [rucio/containers#300]
All other containers seem to have been migrated to Alma 9, end of life for centos 7 is coming closer and I assume that's also the reason why I see warnings about mysql authentication plugins not being found when running against mysql 8.

**Comment by maxnoe** [comment]
Found that FTS is currently not yet supported on Alma 9, this pages says April / May 2024:

https://twiki.cern.ch/twiki/bin/view/LCG/MwOsSupportDetails

**Comment by bari12** [comment]
Yes, but please DO NOT use this container in production anyway, it purely exists for our internal CI/demo purposes. We do not aim to provide a production-level container for FTS, merely have it for the reasons above.

**Comment by maxnoe** [comment]
That is precisely the reason we are interested in it: having a minimal rucio setup in gitlab ci

**Comment by bari12** [comment]
Then let's leave this ticket open until fts is alma9 ready. :-)

**Comment by maxnoe** [comment]
https://fts.web.cern.ch/fts/releases.html FTS 3.13 supporting alma 9 was released a couple of days ago

**Comment by bari12** [comment]
🥳

**Comment by rdimaio** [comment]
docs on upgrading to alma9 https://fts3-docs.web.cern.ch/fts3-docs/docs/install/upgrades/3.13.html

**Comment by maxnoe** [comment]
I think this can just be closed, since #327 and #341 upgraded both fts and fts-cron

**Comment by rdimaio** [comment]
nice, thanks!
