### ISSUE TITLE
allow patching ui containers

### ISSUE THREAD

**Issue by maany** [rucio/containers#331]
Modify the entrypoint script of the UI container to detect and apply any mounted patches before initiating the UI. This enhancement will enable hot patching for UI containers, similar to the current process for Rucio server and daemon containers.

**Comment by rdimaio** [comment]
for reference - this was present in the old UI:

https://github.com/rucio/containers/blob/7c4591358ed6940cc33130603877e7962af0549f/webui/docker-entrypoint.sh#L43-L91

**Comment by rdimaio** [comment]
> @rdimaio that's the new UI (webui) which is already on kubernetes. The script was missing in the old UI which was running on puppet and did not use the same patch mechanism we do in kubernetes :)

thanks for the clarification - if `webui` is the new UI, what's [`ui`](https://github.com/rucio/containers/tree/master/ui)?

**Comment by rdimaio** [comment]
ah I think I get it: `ui` is the old webui, which is the one that's running on Kubernetes, `webui` is the new one which is not yet deployed
