### ISSUE TITLE
Broken link in webui readme

### ISSUE THREAD

**Issue by maxnoe** [rucio/containers#338]
The link to the installation instructions in this section here:
 https://github.com/rucio/containers/tree/master/webui#documentation

is broken

**Comment by rdimaio** [comment]
This was deleted as part of this commit: https://github.com/rucio/documentation/commit/b287be7016edf842dae4f45da1b820dc8075e0a2 - @maany might have more context

**Comment by maany** [comment]
Hey @maxnoe, checkout the containers (webui) and helm charts repositories (rucio-webui) for some instructions on how to deploy the new webui. I could cook up some instructions once I have it running in Atlas ;)

**Comment by maxnoe** [comment]
@maany Thanks, I got it running in the meantime with the docker image without any major issues.

I just wanted to report on the broken link.

You can see the docker compose configuration here: 
https://gitlab.cta-observatory.org/cta-computing/dpps/dpps/-/merge_requests/33/diffs#35b8c13cf2eb2a194eada000eb310d65aed53b2a

**Comment by maxnoe** [comment]
It seems the visualizations (usage graphs etc.) are not working though. Anything else needed for that?

**Comment by maany** [comment]
Hmmm, possibly apache is not liking running in http: ( missing host certs). Are you running in http or https?
Also, are you building this image locally, if not can you try using this guy
https://hub.docker.com/repository/docker/maany/rucio-webui/general 

I made some changes to try out some things on the Atlas side and we do have the graphs rendering there. Please note that the dashboard data is just dummy data as we need to add rucio endpoints that will ultimately expose the required information

**Comment by maxnoe** [comment]
> Are you running in http or https?

https

>  if not can you try using this guy https://hub.docker.com/repository/docker/maany/rucio-webui/general

We are building our own image, but it's just the image here with our policy package added. The link redirects me to the dockerhub login page, so I guess it's private?

**Comment by maxnoe** [comment]
I see the following error on the rse usage page in the javascript console:


![rucio_error](https://github.com/user-attachments/assets/0b8d12a4-068f-4c7e-8921-2c87a87a7dfd)

**Comment by rdimaio** [comment]
We have removed the line pointing to the dead documentation link from the README (as there is no equivalent doc page on how to install the webUI) - once the new webUI will be published for production, we can work on a new documentation page and link it again
