### ISSUE TITLE
Enable Http plugin in xrd containers 

### ISSUE THREAD

**Issue by maany** [rucio/containers#350]

**Comment by panta-123** [comment]
@maany , https/davs protocol already supported in xrootd. The default dev enevironment, XRD5 has xrootd config with http.
The config is passed to xrd5 docker image as: https://github.com/rucio/rucio/blob/master/etc/docker/dev/docker-compose.yml#L243
The config passed is here: https://github.com/rucio/rucio/blob/master/etc/docker/dev/xrd/xrootd.cfg

The xrd5 in default test/dev environment is activated as davs protocol (among others)
https://github.com/rucio/rucio/blob/master/tools/docker_activate_rses.sh#L52

**Comment by maany** [comment]
Thanks a ton for pointing this out @panta-123 :)
