### ISSUE TITLE
webui, x509: Patch apache config to exclude OPTIONS requests from client certificate checks

### ISSUE THREAD

**Issue by maany** [rucio/containers#352]
As discussed with @MytsV, in Firefox, the `HTTP OPTIONS` request to the `/auth/x509/webui` endpoint gets blocked by the Apache proxy of the Rucio Server  as Firefox does not attach the client certificates to OPTIONS requests by default. ( Unlike in Chrome/Safari).

The solution here is to explicitly exclude client certificate checks for OPTIONS requests to the `/auth/x509/webui` endpoint for all browsers.

@MytsV please add details about the firefox settings based on your research to this Issue in a comment, just in case we need them in future.

https://github.com/rucio/containers/blob/f354b67fc5516ac208dbab6f583d5e0ff6096ab3/server/rucio.conf.j2#L51-L54

**Comment by MytsV** [comment]
Authentication failed in Firefox as it does not support including credentials in preflight requests by default. This is configured via `network.cors_preflight.allow_client_cert` preference in about:config. Setting it to true resolves the problem without patching the Apache config, but we cannot rely on users changing their settings.
