### ISSUE TITLE
Trace kronos environment variables are inconsistent 

### ISSUE THREAD

**Issue by ericvaandering** [rucio/containers#52]
Starting here

https://github.com/rucio/containers/blob/18a08051dc0156973b6ce1d9d4ca223a5c003997/daemons/rucio.cfg.j2#L86

some variables are tracer, some are tracer_kronos. Unless this is intentional, they should all be tracer_kronos.

Let me know and I'll fix it and patch it.

**Comment by tbeerman** [comment]
That's definitely not intentional. They should all start with TRACER_KRONOS. If you would fix it that would be much appreciated. Thanks.
