### ISSUE TITLE
Rucio UI containers don't contain requested version

### ISSUE THREAD

**Issue by ericvaandering** [rucio/containers#65]
The UI containers contain the right version of the UI but the wrong version of Rucio. I don't know why yet

1.21.10 and post1 contains 1.22.0.dev2
1.21.12 contains 1.22.rc2

This is causing crashes because things are looking for token auth stuff on a DB that doesn't have the right schema.

**Comment by ericvaandering** [comment]
It looks to me like an issue with PIP. rucio_webui install seems to pull in the very latest rucio install, not the correct version

**Comment by ericvaandering** [comment]
From the build logs:

Collecting rucio_webui[mysql,oracle,postgresql]==1.21.12
  Downloading rucio-webui-1.21.12.tar.gz (464 kB)
  WARNING: rucio-webui 1.21.12 does not provide the extra 'mysql'
  WARNING: rucio-webui 1.21.12 does not provide the extra 'oracle'
  WARNING: rucio-webui 1.21.12 does not provide the extra 'postgresql'
Collecting rucio>=1.2.5
  Downloading rucio-1.22.0.tar.gz (4.5 MB)

**Comment by bari12** [comment]
The `rucio>=1.2.5` is part of the setup.py of the webui package. But I wonder if we need this at all? @tbeerman
