### ISSUE TITLE
Hermes needs sendmail

### ISSUE THREAD

**Issue by ericvaandering** [rucio/containers#68]
The hermes daemon container needs sendmail installed and running. I'm going to hack together something for CMS and then we can discuss if that's the best way or if a more elegant solution is better.

Just FYI

**Comment by ericvaandering** [comment]
@tbeerman I solved this with 

RUN yum install -y sendmail sendmail-cf

and 


if [ "$RUCIO_DAEMON" == "hermes" ]
then
  sendmail -bd 
fi

in start-daemon.sh

Should I prepare this as a PR for general usage?

**Comment by tbeerman** [comment]
Yes, please. I guess in Atlas we would also need this at some point when we are in full kubernetes mode.
