### ISSUE TITLE
WSGI error in latest server image

### ISSUE THREAD

**Issue by davidgcameron** [rucio/containers#72]
I updated to 1.22.3post1 and every request failed with this error
```
[Mon Apr 27 12:45:48.938509 2020] [:error] [pid 3816:tid 139660005021440] [client 158.39.48.13:34468] Embedded mode of mod_wsgi disabled by runtime configuration: /usr/lib/python2.7/site-packages/rucio/web/rest/authentication.py
```
The solution was to set in /etc/httpd/conf.d/rucio.conf:

`WSGIRestrictEmbedded Off`

This was set to On in this commit:

https://github.com/rucio/containers/commit/e7d510b4828fa73c89633d68d59be941d3a646e3

**Comment by tbeerman** [comment]
Hi David,
I cannot replicate this. It's working fine in our kubernetes servers when deployed with helm.
How do you run the container? What variables do you set.

**Comment by davidgcameron** [comment]
```
docker run --network dev_default --name=rucio-server -v /etc/grid-security/certificates:/etc/grid-security/certificates -v /etc/grid-security/hostcert.pem:/etc/grid-security/hostcert.pem -v /etc/grid-security/hostkey.pem:/etc/grid-security/hostkey.pem -v /opt/rucio/etc:/opt/rucio/etc -v /home/centos/dev/rucio/bin/:/opt/rucio/bin -v /home/centos/dev/rucio/tools:/opt/rucio/tools -v /home/centos/dev/rucio/lib:/opt/rucio/lib -p 443:443 --env-file=/home/centos/rucio-server-env -d rucio/rucio-server
```
where rucio-server-env contains
```
RUCIO_ENABLE_SSL=True
RUCIO_HOSTNAME=act-ldmx.cern-test.uiocloud.no
RUCIO_CA_PATH=/etc/grid-security/certificates
RUCIO_ENABLE_LOGFILE=True
```
then I added the line to rucio.conf to set the alias for /auth as mentioned in the other ticket.

**Comment by tbeerman** [comment]
Okay thanks. Did you actually add the authentication endpoint with the process groups? I.e.,

`WSGIScriptAlias /usr/lib/python2.7/site-packages/rucio/web/rest/authentication.py process-group=rucio application-group=rucio`

That could be the issue and would also be fixed with the other ticket.

Something else: why are you mounting all your local rucio folders? It's all already contained in the image. You can mount rucio.cfg in `/opt/rucio/etc` if you don't want to use the env variables to automatically create it. But other than that you don't have to mount `bin`, `tools` and `lib`

**Comment by davidgcameron** [comment]
Ah, I was just copying this line from an older installation and didn't notice the new parts on the end of the other lines :) I added them and now it works with `WSGIRestrictEmbedded On`

I'm mounting the local folders to bootstrap the database with `tools/run_tests_docker.sh -i`, following the instructions for the dev container. Is there a better way?

**Comment by tbeerman** [comment]
I have an init container written for the kubernetes tutorial at the workshop. I can make that available in the Rucio repository on docker hub.

**Comment by bziemons** [comment]
@davidgcameron I think this can be closed?

**Comment by davidgcameron** [comment]
Yes, please go ahead.
