### ISSUE TITLE
Add variable to enable auth server

### ISSUE THREAD

**Issue by davidgcameron** [rucio/containers#73]
When I set up the server I have to manually add this line in the apache config to enable the auth server:

` WSGIScriptAlias /auth                   /usr/lib/python2.7/site-packages/rucio/web/rest/authentication.py`

It would be good if this could be enabled through an env var.

**Comment by tbeerman** [comment]
Hi David,
I have this change already in my local branch for the python 3 containers. I'll add it as well for python 2 and I'll push it soon.
