### ISSUE TITLE
Making conversion of the clients container to Singularity possible

### ISSUE THREAD

**Issue by ygrange** [rucio/containers#95]
I would like to start the discussion on how the container could be made executable using Singularity in stead of Docker. 
In the ESCAPE project, we did modify the container so it would run in user space in stead of as root (this is in itself probably a topic worth some discussion). I then changed it again so that not only the execution is in user space, but also the creation of the config file. 

The repo is here: https://github.com/ESCAPE-WP2/rucio-client-container

It was pointed out to me by @mlassnig that the policy of the project is to prevent diverging releases. So I decided to open this as an issue upstream. 

Before trying to apply the changed to this upstream repo I think it's wiser to first have a look at it together with you and hear your thoughts.

**Comment by tbeerman** [comment]
Hi @ygrange,

thanks for sharing this. As far as I can see the only difference (other than VO-specifics) is the switch from root to user space. We can certainly add that to the base client container as well. We will also need this for ATLAS image and maybe it's also useful for others. Is there anything else that is needed for Singularity?

**Comment by ygrange** [comment]
Adding @rohinijoshi06 to the convo in case she has to add anything here :). 

For Singularity the importand bit is that one can not rely on root user doing anything at run time. So basically that is the only change. Also in Singularity I will have to bind in the rucio.cfg enclosing directory so the creation of the cfg file only happens at first execution. I think I tried just making /opt/rucio/etc having permissions 777 but that didn't seem to work out too well either.

One thing is that X509 authentication works much better with Singularity because Docker always has these annoying issues with user ids not being the same between host and container (so the user inside the container has e.g. id 1000 and the user on the host system has 1024, then binding the key/crt files in the container will give some nasty access denieds).

**Comment by ygrange** [comment]
One other thing I was playing around with was adding CI to the repo we have (after I managed to break it). It is a pretty minimal check that basically lets the rucio python library read out the config keys provided by the command line (basically a minimal check of the documentation; assuming that rucio itself has its own CI or tests). Just linking to it https://github.com/ygrange/rucio-client-container/tree/travis . May be relevant to you, may be a bit overengineered.

**Comment by ygrange** [comment]
Just wanting to check whether this issue is not percieved as being blocked. I checked with anybody relevant and they are ok with this being set in motion.

**Comment by tbeerman** [comment]
Hi @ygrange, sorry for the delay. I've now pushed a PR which adds a separate user and changes the ownership of the configuration to that user https://github.com/rucio/containers/pull/99

So for your VO-specific container you would just have to the certificates and vomses.
Does that look okay to you?

**Comment by ygrange** [comment]
I'll pull it over, build it and Singularize to test and ping you :).

**Comment by ygrange** [comment]
I submitted a pull request for your pull request...

**Comment by tbeerman** [comment]
Where did you submit that?

**Comment by ygrange** [comment]
Doesn't look like I completely understand the workflow if you have to ask. It's here:
https://github.com/tbeerman/containers/pull/1

**Comment by tbeerman** [comment]
Ah okay, I see. You opened the PR against my personal repo. That one is only for my changes that I want to submit to upstream (this repo). You should submit the PR here.

**Comment by ygrange** [comment]
Ah ok. My idea was to submit a pull request on your pull request, but I guess this works as well. 

I propose some changes to your pull request to make Singularity work as well. The issue with the previous setup was that /home gets automatically mounted in in Singularity, so anything that is put there will basically not be available inside a Singularity container.

I tested this works in Singularity. I have to admit I didn't fully test the functionality in Docker.

**Comment by ygrange** [comment]
So I think the pull request was merged and therefore this issue can be closed. Only question I have now is: what is the procedure for pushing the containers to docker hub (i.e. when can I basically rewrite the ESCAPE Dockferfile to use this version)? 
Thanks a lot!

**Comment by tbeerman** [comment]
We have an auto-build procedure running on docker hub so every upcoming release will now use this. Additionally, I will manually re-build and push 1.22.8 and 1.23.5, which are the current default and testing versions for ATLAS. Do you need any other version?

**Comment by ygrange** [comment]
I'm a bit of a rucio noob I have to admit. So the current container is built on `release-1.22.6.post1`. Current server runs on `1.23.6`. I am not sure if backwards compatibility is an issue. Let's see if I can draw @riccardodimaria in to comment on this.

**Comment by riccardodimaria** [comment]
May you please have 1.23.6 as well since server and webui use that?

**Comment by tbeerman** [comment]
Okay, I've now pushed the new images for 1.22.8, 1.23.5 and 1.23.6 both for python2 and 3.
